# Generated by Django 5.1.4 on 2024-12-16 14:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Manual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.BooleanField()),
                ('message', models.TextField()),
                ('voice', models.URLField()),
                ('time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='VAD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.BooleanField()),
                ('message', models.TextField()),
                ('voice', models.URLField()),
                ('time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('title', models.CharField(max_length=100)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vad_free', models.BooleanField(default=True)),
                ('vad_url', models.TextField()),
                ('manual_free', models.BooleanField(default=True)),
                ('voice', models.CharField(max_length=7)),
                ('instruction', models.TextField()),
                ('manual', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.manual')),
                ('vad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.vad')),
            ],
        ),
    ]
