# Generated by Django 5.1.4 on 2025-01-05 15:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('title', models.CharField(max_length=100)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('time', models.DateTimeField(auto_now=True)),
                ('model', models.TextField(null=True)),
                ('voice', models.CharField(max_length=7)),
                ('temperature', models.FloatField(null=True)),
                ('instruction', models.TextField(null=True)),
                ('vad', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Memory',
            fields=[
                ('role', models.BooleanField(default=False)),
                ('message', models.TextField(null=True)),
                ('voice', models.TextField(null=True)),
                ('time', models.DateTimeField(auto_now=True)),
                ('serverid', models.TextField(null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('conversation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='memory', to='core.conversation')),
            ],
        ),
    ]
