# Generated by Django 5.1.4 on 2025-01-06 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='key',
            field=models.TextField(null=True),
        ),
    ]
