# Generated by Django 5.1.4 on 2025-01-06 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_conversation_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='key',
            field=models.TextField(default='None', null=True),
        ),
    ]
