# Generated by Django 5.1.4 on 2024-12-17 14:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_conversation_manual_alter_conversation_vad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='manual',
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='vad',
        ),
        migrations.AddField(
            model_name='manual',
            name='conversation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='manuals', to='core.conversation'),
        ),
        migrations.AddField(
            model_name='vad',
            name='conversation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='vad', to='core.conversation'),
        ),
    ]
