# Generated by Django 5.1.4 on 2024-12-17 14:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_conversation_manual_remove_conversation_vad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manual',
            name='conversation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manuals', to='core.conversation'),
        ),
        migrations.AlterField(
            model_name='vad',
            name='conversation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vad', to='core.conversation'),
        ),
    ]
