# Generated by Django 5.1.4 on 2024-12-17 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_manual_conversation_alter_vad_conversation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vad',
            name='conversation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vads', to='core.conversation'),
        ),
    ]
