# Generated by Django 5.1.4 on 2024-12-17 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_vad_conversation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manual',
            name='conversation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manual', to='core.conversation'),
        ),
        migrations.AlterField(
            model_name='vad',
            name='conversation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vad', to='core.conversation'),
        ),
    ]
