# Generated by Django 5.1.4 on 2024-12-28 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_manual_conversation_alter_vad_conversation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manual',
            name='voice',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='vad',
            name='voice',
            field=models.TextField(),
        ),
    ]
