# Generated by Django 5.1.4 on 2024-12-28 13:26

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_manual_voice_alter_vad_voice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manual',
            name='id',
        ),
        migrations.RemoveField(
            model_name='vad',
            name='id',
        ),
        migrations.AddField(
            model_name='manual',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='vad',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
