# Generated by Django 5.1.4 on 2025-01-04 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_vad_conversation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='temperature',
            field=models.FloatField(null=True),
        ),
    ]
