# Generated by Django 5.1.4 on 2025-01-05 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_conversation_temperature'),
    ]

    operations = [
        migrations.RenameField(
            model_name='memory',
            old_name='serverID',
            new_name='serverid',
        ),
    ]
